name: ci

on:
  push:
  schedule:
    # https://crontab.guru/every-day
    - cron:  '0 9 * * *'

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lints Pull Request commits
        uses: wagoid/commitlint-github-action@v2

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Read node version from `.nvmrc` file
        id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvmrc.outputs.node_version }}

      - name: Install npm dependencies
        run: npm install --progress=false --loglevel=warn --ignore-scripts

      - name: Check typescript compilation
        run: npm run typecheck

      - name: Lint code
        run: npm run lint

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Read node version from `.nvmrc` file
        id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvmrc.outputs.node_version }}

      - name: Install npm dependencies
        run: npm install --progress=false --loglevel=warn --ignore-scripts

      - name: Build dist
        run: npm run build:dist

  coverage:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [12, 14]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm install --progress=false --loglevel=warn --ignore-scripts

      - name: Run tests
        run: npm run coverage:all
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          MAP_QUEST_API_KEY: ${{ secrets.MAP_QUEST_API_KEY }}
          HERE_APP_ID: ${{ secrets.HERE_APP_ID }}
          HERE_APP_CODE: ${{ secrets.HERE_APP_CODE }}

      - name: Coveralls
        uses: coverallsapp/github-action@master
        if: startsWith(matrix.node-version, '14')
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
